### ISSUE TITLE
suivi individuel des congés

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#11]
Dans le suivi individuel des congés, il faudrait qu'apparaissent : 
 + les congés code 950
 + les jours d'ancienneté code 951
 + les jours de fractionnement code 952 (tu n'en auras pas pour l'instant car ils ne sont que sur la période d'hiver)
 + les ponts code 955
 + quand cela sera créé, il y aura aussi les jours de "congés solidarité". Ceux-ci ne doivent pas apparaitre dans le planning car ils sont travaillés, mais doivent alimenter le suivi des congés (code 950) car ils en font partie.
Je t'envoie par mail ce que Célia faisait pour que tu visualises à quoi cela peut ressembler.
Merci

**Comment by Highbrainer** [comment]
J'ai un premier jet, mais il me manque l'info de ce qui a été acquis...

**Comment by Highbrainer** [comment]
Pour mémoire:
* Je n'ai pas fait la somme de chaque tableau
* Aussi, je n'ai pas tracé les bordures de chaque tableau
* Enfin, je n'ai pas mis de mot de passe aux fichiers

_Est-ce nécessaire??_
