### ISSUE TITLE
Entretien pro - soucis à l'ajout de souhaits

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#12]
Je pense qu'il faut changer le mode de renseignement des formations demandées parce que j'ai perdu l'info pour plusieurs salariés et ça va pas le faire.
Tant pis si c'est moins joli mais faut vraiment que je loupe rien!
Merci

**Comment by Highbrainer** [comment]
Ça me semble prioritaire!
Le truc, c'est qu'il faut que je relivre une version du serveur, pour ça...

**Comment by Highbrainer** [comment]
Si on clique directement sur save après avoir saisi le libellé du souhait, celui-ci n'est pas enregistré, et on garde "Saisir votre souhait" à la place....
En attendant une correction, il faut cliquer par exemple dans un autre champ avant de sauver ou valider...
