### ISSUE TITLE
formation - DPC

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#13]
quand je rentre une formation il faudrait que je puisse indiquer s'il s'agit d'une formation DPC quelque part.
Cela me permettrait ensuite de faire un export uniquement sur les formations DPC.
pour info il faut que tous les dentistes, opticiens et audioprothésistes fassent une formation DPC tous les 3 ans...
donc dans l'idéal il faudrait que je récupére toute la liste des salariés concernés (en fonction de leur emploi) et qu'en fasse tu indiques la date de leur dernière formation DPC.
J'en veux des choses!!!

**Comment by Highbrainer** [comment]
J'ai d'ores et déjà ajouté le champ dpc (true/false) pour les formations, éditable dans le backoffice.
Je vais ajouter un nouvel export avec les colonnes suivantes:
* nom/prénom
* établissement
* emploi courant
* date de la formation dpc la plus récente.

On pourrait ajouter un indicateur de couleur (vert si moins de 30 mois, orange si 31-36 mois et rouge si plus de 3 ans ....? 
Souhaites-tu un onglet par emploi.
Souhaites-tu inclure tous les emplois ou seulement un sous-ensemble? Ou seulement ceux pour lesquels il existe au moins un salarié qui a une formation dpc???...???

**Comment by Highbrainer** [comment]
J'ai ajouté le nouvel export "Dernière formation DPC" dans la vue des Exports du backoffice 1.1
Cela génère un fichier excel à 6 colonnes: 
* nom/prénom
* établissement
* emploi courant
* date de la formation dpc la plus récente.
* nom de la formation
* nom de l'organisme de formation

@MagaliBorgoltz peut-être faudrait-il n'inclure que les salarié encore présents dans l'entreprise (pas de date de sortie de l'entreprise ou dans le futur...) ???

**Comment by Highbrainer** [comment]
Au final on a dit qu'on ajouterait un attribut booléen sur l'emploi qui indique que les salariés correspondants sont soumis au DPC. L'export ne devra concerner que les salariés actuellement dans cet emploi. A faire!

**Comment by Highbrainer** [comment]
La partie serveur a été livrée en v1.1 .
La partie BO sera livrée en v1.1.1
