### ISSUE TITLE
Entretien Annuel

### ISSUE THREAD

**Issue by Highbrainer** [Highbrainer/jeevaneo#18]
L'entretien annuel partage les éléments suivants avec l'entretien pro:
* le cartouche "mémorisé" de l'état du salarié au moment de l'entretien (emploi, ancienneté, responsable...)
* une liste d'évaluation des sessions de formations qui ont eu lieu depuis l'EA précédent
* une liste des souhaits de formation, qui lui est propre
* une liste des souhaits par l'entreteneur de formations, qui lui est propre aussi.

_De facto_, la liste des evaluations à afficher dans l'EP sera pré-remplie par au moins un EA (voir deux!).

Le formulaire de saisie des formations doit rendre obligatoire l'évaluation de chaque session concernée.
Par défaut, aucune évaluation n'est pré-renseignée (actuellement, on a "satisfaisant" par défaut dans l'EP...), sauf si elle a déjà été évaluée dans un entretien précédent évidemment.

Pour rendre évident graphiquement que certaines formations ont déjà été évaluées et ne nécessitent pas plus d'effort, on pourra séparer dans le formulaire deux tableaux
1. l'un, readonly, des formations déjà évaluées précédemment
1. l'autre, en modification obligatoire, des formations à évaluer, le cas échéant.

_Dans le pdf généré, on fusionnera cela en un unique tableau._

**Comment by Highbrainer** [comment]
Un EA porte une liste d'objectifs pour l'année suivante. 
Il porte aussi une évaluation des objectifs définis à l'EA précédent, qui devra donc être pré-remplie avec les objectifs de l'EA précédent. Si cet EA n'existe pas dans GIC, il faut que l'entreteneur puisse saisir le texte des objectifs en question.

**Comment by Highbrainer** [comment]
Pour l'évaluation des compétences et des comportements, il faut ajouter une option "Non concerné" en sus de "-", "-/+" et "+", ne pas sélectionner de valeur par défaut et rendre chaque ligne obligatoire.

**Comment by Highbrainer** [comment]
@MagaliBorgoltz j'ai pas trop mal avancé.
Il me reste à faire :
* les missions spécifiques et principales ajoutées ne sont pas enregistrées
* les évaluations et évolutions de savoir être et de compétences ne sont pas enregistrées
Je continue demain! :)

**Comment by Highbrainer** [comment]
@MagaliBorgoltz Ensuite il me restera aussi la génération du pdf correspondant à la validation, ainsi que les règles de validation (les champs obligatoires etc.)

**Comment by Highbrainer** [comment]
@MagaliBorgoltz J'ai bien avancé - les evaluations de missions principales et spécifiques, de compétences et de savoir etre me semblent bien gérées.
J'ai aussi modifié les couleurs de la page pour qu'on distingue bien un EAE d'un EP.
Il manque toujours dans l'EAE le tableau des objectifs de l'année précédentes.
Et il manque le modèle de génération du pdf... Ce sera pour demain!

**Comment by Highbrainer** [comment]
@MagaliBorgoltz Tout semble fonctionner sauf : 
* la mise à jour des objectifs de l'année prochaine (je crois qu'il faut tester toutes les mises à jour...
* la génération du pdf : le template n'est pas encore fait!

**Comment by Highbrainer** [comment]
@MagaliBorgoltz Soucis de mise à jour corrigé. 
Il reste la génération du pdf...

**Comment by Highbrainer** [comment]
@MagaliBorgoltz Bon, j'ai un premier jet, mais il nécessite des tests de ta part. 
Je n'ai pas encore les "catégories de compétences" et le champ d'un nouvel objectif reste valorisé à "Décrire l'objectif ici" ... mais sinon ça a l'air utilisable...
J'espère!!

**Comment by Highbrainer** [comment]
@MagaliBorgoltz On progresse encore un peu :) Les skins sont OK, y compris celle de la liste des personnes. Et les boutons de création d'entretiens sont aux couleurs respectives de leurs formulaires.
En plus en cas de formulaire déjà validé, on reçoit un message clair à l'enregistrement...
Il reste à faire la popup qui se pré-remplit avec "Décrire l'objectif ici"

**Comment by Highbrainer** [comment]
@MagaliBorgoltz J'ai finalement réussi à obtenir un truc. C'est pas encore ultimement parfait, tu me diras si ça te va. Quand tu ajoutes un objectif, ça t'ouvre direct la "bulle de saisie de la description. Et tu peux ajouter des retours à la ligne avec shift+enter, puis quand tu fais entrée, ça ferme la bulle ...
Je ne sais pas si je suis clair.......

**Comment by Highbrainer** [comment]
@MagaliBorgoltz J'ai une nouvelle version qui semble bien générer ses pdfs même quand les champs ne sont pas remplis. 
Les sessions de formations "déjà évaluées depuis le dernier entretien du même type" sont gérées aussi. Deux tableaux différents dans le formulaire (un "lecture seule" et un de saisie) et mélangés dans un unique tableau dans le pdf. 
J'ai quasiment terminé de préparer le livrable (il me faut le portable de Maiann qui est en bas et en veille ou éteint, je finirai demain matin.
Ce qu'on peut faire, c'est le tester ensemble demain soir et j'enverrai le tout ensuite à Jean.
J'espère que cette fois c'est bon!

Sinon j'ai trouvé un "bug" : tous les entretiens qui ont déjà été saisis par le passé n'ont pas de "photo" du salarié au moment de l'entretien. Et ça fait planter la génération du pdf. Alors, j'ai écrit une petite routine de nettoyage, sous la forme d'une URL à appeler dans le navigateur. J'ai ajouté ça en dernière étape de la procédure de migration...

**Comment by MagaliBorgoltz** [comment]
Ok !
On a ce soir (mais y a papa) et j ai demain aussi !
Merci
Je t ❤️
Magali

Le mardi 6 juin 2017, Alexandre Borgoltz <notifications@github.com> a
écrit :
