### ISSUE TITLE
Export des responsables par salarié

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#2]
Il faudrait un export excel de la liste des salariés avec
* nom d'établissement
* nom du salarié
* prénom
* nom du responsable
* nom du ou des entreteneurs

Il faudrait filtrer sur les gens présents au jour J (date de sortie absente ou dans le futur).

**Comment by MagaliBorgoltz** [comment]
Merci d'avance! 👍

**Comment by Highbrainer** [comment]
C'est fait dans la 1.0.8! :)

**Comment by Highbrainer** [comment]
@MagaliBorgoltz Peux-tu fermer la demande (close the issue) si le résultat te va?
