### ISSUE TITLE
bug 2 et 3 (à moins que les deux soient liés)

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#22]
Je suis allée sur Réjane Arrignon.
Elle avait un entretien pro fait par Lionel l 11/08/2016.
J'ai pas bien vu s'il était validé ou non (mais possible qu'il soit pas validé)
J'ai cliqué sur "nouvel entretien pro" --> Lionel a disparu et c'est moi qui suis devenue meneur pour l'entretien pro en date du 11/08/2016 (il n'a pas créé de nouvel entretien à la date d'aujourd'hui)
quand je vais voir le formulaire, il y a un problème au niveau des dates
date du précédent entretien : 07/06/2017
date de l'entretien : 11/08/2016
Rien n'est renseigné (donc j'ai perdu ce qui était fait par Lionel)
j'ai une formation undefined undefined
Je ne vois aps la formation que je lui ai rentrée hier en date du 30/05/2017 (l'ai-je mal renseignée?)

Ensuite j'ai fait un nouvel EAE : toutes les formations apparaissent dans formations déjà évaluées alors que je n'ai pas validé l'entretien pro.... je pensais qu'il fallait que j'attende de valider l'un pour que ca passe en déjà validées dans l'autre.
J'ai validé sans rien renseigner ---> BOUM (message d'erreur envoyé par mail)
Je mets dans le même message car c'est peut être lié

**Comment by Highbrainer** [comment]
Le crash à la fin est corrigé par #25 .

**Comment by Highbrainer** [comment]
Pour les dates des précédents entretiens, c'est résolu avec #24

**Comment by Highbrainer** [comment]
Pour la perte des données de LIonel... elles n'y étaient pas!!!

**Comment by Highbrainer** [comment]
le reste est résolu dans la #30
