### ISSUE TITLE
bug 5

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#24]
josiane sauboua a un entretien pro d'août 2016 qui n'a pas été validé.
Je suis allée le voir et y'a un problème comme pour Réjane Arrignon : date du précédent entretien = date d'aujourd'hui

**Comment by Highbrainer** [comment]
Je ne reproduis plus le soucis avec la dernière version du nettoyage des photos manquantes.

**Comment by Highbrainer** [comment]
Je vais ajouter un check des dates quand même pour être sûr.

**Comment by Highbrainer** [comment]
Résolu, avec une URL pour vérifier que tout va bien : 
http://rh-gic:...../rest/entretiens/check-photos
