### ISSUE TITLE
salarié sorti

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#26]
quand un salarié a une date de sortie, il faudrait que les responsables ne le voit plus dans la liste des salariés pour lesquels ils peuvent faire un entretien.
Pour moi, il faudrait également qu je ne  vois plus dans la liste des salariés à qui je peux faire un entretien.
Par contre il faut que je continue à les voir dans le back office 
faut vérifier que ca ne fonctionne pas déjà comme ça... mais je ne suis pas sure!

**Comment by Highbrainer** [comment]
@MagaliBorgoltz Pour l'instant, 
* les gens normaux ne voient qu'eux même
* les entreteneurs ne voient que leurs entretenus, et ne les voient plus après leur date de sortie
* les RH voient tout le monde, même après la date de sortie
C'est très simple à changer... mais ça nécessite de relivrer le serveur...
