### ISSUE TITLE
pas pressé : ancienneté dans le poste actuel

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#27]
dans son entretien pro, Isabelle Boucq a une ancienneté dans le poste actuel de renseigné.
Je croyais que ce n'était le cas pour personne.
Est-ce que c'est parce que j'ai rentré cette donnée sur elle pour faire un test?
par exemple sur moi aussi j'ai cette info
alors que Pascal Bernard par exemple n'a pas cette info.
FAudrait juste vérifier sur Isabelle et moi dans le back office s'il y une date de renseignée.
Dans ce cas c'est qu'un jour je me suis lancée dans la saisie de cette info mais que je ne l'ai fait que pour le début des services communs....
Si c'est le cas, on oublie ma demande. c'est juste une vérification

**Comment by Highbrainer** [comment]
Tu avais saisi certaines dates à la main...
