### ISSUE TITLE
classer par ordre alphabétique

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#34]
Il faudrait, si possible qu'on puisse classer les formations par ordre alphabétique parce que je je commence à en avoir plusieurs pour un même organisme de formation et ca devient difficilement lisible.
Merci :)

**Comment by Highbrainer** [comment]
Tu veux dire un tri par libelle de formation, au sein de chaque organisme?

**Comment by MagaliBorgoltz** [comment]
yes
