### ISSUE TITLE
question salariés entretenus

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#35]
J'ai un doute.
A l'optique de Niort, il y a plusieurs entreteneurs possible.
Mais pour 4 de ces entreteneurs (d'arlhac antoine, jérémy leglise, anne paitraud et solene pichavant) il n'y a qu'un entreteneur : Marielle.
Mais du coup, dans la fiche de Marielle, pour "salariés entretenus" il n'y a d'écrit que ces 4 personnes. On est ok qu'elle peut entretenir tous les autres également? J'ai un doute d'un coup

**Comment by Highbrainer** [comment]
Non, pour pouvoir éditer un entretien, il faut soit
* être l'employé lui-même
* être un entreteneur explicite de l'employé
* avoir le rôle DRH (toi et Isabelle, de mémoire)

Si tu veux que Marielle puisse faire un entretien à tous les employés de l'établissement, il faut l'ajouter dans la liste des entreteneurs de l'établissement...
