### ISSUE TITLE
objectifs dans la fiche du salarié

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#39]
il faudrait retester mais a priori on a fait un entretien bidon avec Christine, avec des objectifs, on a validé.
On est ensuite retourné voir la fiche du salarié mais c'était toujours les objectifs de l'année dernière...
Peut-être qu'il faut que la journée se termine avant qu'ils apparaissent?

**Comment by Highbrainer** [comment]
Bizarre...
J'espère que je ne me suis pas gourré et que je n'ai pas affiché les
objectifs du premier entretien (au lieu de prendre le dernier) ??!!?
