### ISSUE TITLE
Responsables et entreteneurs

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#4]
Lorsqu'on rattache un employé  à un établissement, il faut renseigner le responsable et les entreteneurs de cet employé avec ceux de l'établissement. 
Ces valeurs peuvent être modifiées à la main dans le backoffice.
En cas de changement d'établissement, on réécrase avec ceux du nouvel établissement.

**Comment by Highbrainer** [comment]
J'ai ajouté le lien entre un établissement et ses entreteneurs (ETABLISSEMENT__ENTRETENEURS).
Un employé hérite les entreteneurs de son établissement, sauf s'il a des entreteneurs spécifiques (EMPLOYE__ENTRETENEURS).

Il reste à écrire un script one-shot de reinit des entreteneurs d'employés, qui mettra à nul les entreteneurs d'employes qui sont identiques à ceux de leur établissement...
