### ISSUE TITLE
Date et type d'entretien dans l'export des souhaits formation

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#42]
Tu m'as déjà créé un export pour obtenir les souhaits de formation des salariés.
Maintenant que nous avons plusieurs types d'entretien et également plusieurs entretiens du même type d'enregistrés pour une même personne, il faudrait que je puisse choisir quel type d'entretien et quelle date (année)
Ou alors ajouter ces données pour que je puisse faire des filtres....
Merci :)

**Comment by MagaliBorgoltz** [comment]
dans l'export "demande de formation" que tu m'as déjà fait, il y a dans les en-tête de colonne "avis de l'évaluation" au lieu de "avis de l'évaluateur"... oui je sais je chipote!

**Comment by Highbrainer** [comment]
Finalement, on a décidé de ne pas se restreindre aux souhaits du dernier entretien, et de garder tous les souhaits de tous les entretiens. Magali triera sur la date dans excel.

**Comment by Highbrainer** [comment]
Doublon partiel de #48
