### ISSUE TITLE
Problème sur la liste des formations déjà évaluées qui apparaisent 

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#43]
Il y a clairement un problème sur les formations…. Je vois celles qui sont avant l’EAE de 2016
Exemple : Pascale Baradeau : sur son EAE créé je vois accompagner la fin de vie en décembre 2015 alors qu’elle a eu un EAE en 2016…
C’est con ça !

Mais j'ai effectué d'autres tests et par exemple Sophie BAconneau : pas de formation depuis le dernier entretien.... et ca je suis ok
Leslie Gola : 2 formations apparaissent, faites après le dernier EAE je suis ok
Philippe Lelong : plusieurs formations apparaissent, toutes bien après le dernier EAE....
Alors pourquoi sur la première ca ne fonctionne pas?

**Comment by MagaliBorgoltz** [comment]
ah non attends....
en fait sur Pascale Baradeau, la formation qui apparait n'est pas modifiable.... elle a dû être évaluée lors du dernier Entretien pro. et je comprends mon problème.
l'entretien pro a été validé au mois de novembre alors que l'EAE a eu lieu en octobre.... ce qui explique pourquoi il le fait apparaitre.... 
Donc c'est normal... tout va bien en fait. Ou du moins tout s'explique.
Désolée du dérangement :)

**Comment by Highbrainer** [comment]
J'ai ajouté un filtre pour ne conserver que les formations qui ont eu lieu après le dernier entretien du même type.
