### ISSUE TITLE
export des demandes de formations

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#48]
J'ai l'impression que l'export "souhaits de formations" ne reprend que les souhaits émis dans les entretiens pro et pas dans les EAE.
Je dis ça parce que je viens de faire un export et j'ai aucune demande de cet été alors que des EAE ont eu lieu et des demandes ont été faites...
Merci :)

**Comment by MagaliBorgoltz** [comment]
Alors je sais que la semaine est bien chargée et je peux encore attendre un peu...
Mais d'ici 15 jours ca serait cool que je puisse exporter les demandes de formation des EAE....
Mais je suppose que c'est pas grand chose pour toi... :)

**Comment by Highbrainer** [comment]
On regarde ce soir après la sous-couche :)

2017-08-17 9:54 GMT+02:00 MagaliBorgoltz <notifications@github.com>:

**Comment by MagaliBorgoltz** [comment]
Je pense pas non .... Y a pas du foot ;)
Ça peut attendre c est juste pour ne pas oublier

Le jeudi 17 août 2017, Alexandre Borgoltz <notifications@github.com> a
écrit :

**Comment by Highbrainer** [comment]
La #42 répond à cette demande.
