### ISSUE TITLE
récapitulatif des EAE et des Entretiens pro

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#51]
C'est pas pressé et je pense pas très long pour toi mais dans l'idéal il faudrait que je puisse imprimer un tableau reprenant pour chaque service le nom, le prénom, la date de l'entretien, le nom de l’entreteneur.
Je t'envoie par mail un exemple de ce que je faisais à la main jusque -là!
Merci

**Comment by Highbrainer** [comment]
Convenu ensemble : on laisse tomber, au profit des fichiers d'export des dates d'entretiens
