### ISSUE TITLE
chèques déjeuner - problème pour le choix des salariés

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#60]
J'ai un problème pour une salarié.
Je lui ai mis un choix de 15 chèques dej max mais finalement elle en veut le max.
Problème je n'arrive pas à enlever le 15; Si je le supprime et ne le remplace par rien.... il revient.
Si je le remplace par 0, elle ne va pas avoir de chèques déjeuner.
comment dois-je faire?

**Comment by Highbrainer** [comment]
Tu fais un clic droit sur le titre de la ligne, pas sur la zone où tu peux
taper quelque chose, puis tu cliques sur "Restore Default Value" .

Le 21 septembre 2017 à 15:30, MagaliBorgoltz <notifications@github.com> a
écrit :

**Comment by MagaliBorgoltz** [comment]
c'est magique :)
Merci
