### ISSUE TITLE
problème EAE chantal Bonnaud

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#61]
La boulette, je n'ai pas enlevé la seconde Chantal Bonnaud et elle a son EAE ce matin
Du coup il n'y a pas d'objectif de l'année dernière car ils sont enregistrés sur l'autre Chantal.
La responsable a déjà fini ou presque l'EAE .
J'ai pas réussi à ajouter les objectifs précédents dans l'EAE.
DOnc j'ai dit à la responsable de me noter du un papier s'ils étaient atteints, les commentaires pour que je l'intègre ensuite dans l'EAE.
Il faudrait juste que tu me dises comment faire pour ne pas faire de bêtise, mais on peut regarder ça un soir c'est pas à la seconde maintenant.
Merci

**Comment by Highbrainer** [comment]
Tu drag'n drop les entretiens de la mauvaise Chantale vers la bonne Chantale, puis dans l'EAE courant, via AddChild, tu ajoutes autant de "Objectif Précédent" que d'objectifs dans l'EAE précédent.
Et pour chaque OP, tu choisis (vue properties) l'objectif en question.
Puis tu faire sortie la mauvaise Chantal, tu enregistre et tu vas vérifier dans les pages GIC correspondantes...
