### ISSUE TITLE
problème export excel dernières formations DPC

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#72]
J'ai un problème, je n'arrive plus à obtenir de fichier excel reprenant les dernières formations DPC de chacun.
Quand je clique sur "dernière formation DPC", il me demande où je souhaite le mettre.
Il semble travailler mais il ne me dit jamais que c'est ok.
Il y a bien un fichier de créé mais quand je l'ouvre il me dit "le format du fichier que vous tentez d'ouvrir est différent de celui spécifié par l'extension du fichier".
Et quand je l'ouvre quand même il est vide.
C'est étrange parce que ca a déjà marché....

**Comment by Highbrainer** [comment]
Ca vient probablement d'un (au moins) employé qui n'a pas d'affectation courante d'emploi.
