### ISSUE TITLE
import dans GIC des temps de travail

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#73]
Il faut que j’intègre les temps de travail et je ne me souviens plus comment….
C’était un fichier avec matricule, nom, prénom, temps de travail ?
Il faudrait que tu me redonnes ce que tu attends car je ne crois pas avoir bien fait la GA depuis la paie.
Merci

**Comment by Highbrainer** [comment]
Il s'agit d'un fichier csv.
Le séparateur est le point-virgule.
L'encodage est ISO-8859-1 (isolatin 1).
La première ligne contient les titres de colonnes.
La première colonne est le matricule, entre guillemets. La 11ème colonne est l'horaire entre guillements.
Les autres champs sont ignorés.

**Comment by Highbrainer** [comment]
Je crois qu'on peut considérer que cette demande est en doublon avec #85 :)
