### ISSUE TITLE
chèques déjeuner - supprimer établissement dentaire la pallice

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#84]
Il n'y a plus personne au dentaire la pallice donc j'ai Johnny qui ressort...
Moi je m'en fiche mais c'est pour faire plus sérieux vis à vis du remplaçant.
Comment je peux faire? J'ai pensé à supprimer cet établissement mais j'ai peur de faire des bêtises!
Merci

**Comment by Highbrainer** [comment]
J'ai remplacé Johnny par "Pas d'employé dans cet établissement!"
