### ISSUE TITLE
intégration du temps de travail des salariés

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#85]
Si tu te souviens, dans la liste à compléter par les salariés pour les chèques déjeuner on indique temps plein ou temps partiel.
il faudrait que tu me remontres où il va chercher cette info car a priori quand il y a un changement dans la paie, ca ne modifie pas l'indication.
Exemple : salarié 1272 qui est à temps partiel maintenant ou salarié 2157 qui est aussi passée à temps partiel.
Peut-être que lorsque j'intègre les salariés je ne mets pas le temps de travail.
Bref, si on pouvait regarder ensemble 2 minutes ça serait cool.
Merci

**Comment by Highbrainer** [comment]
Il faut utiliser le clic droit "Importer les temps de travail" sur la racine "Cheque Dej" ou sur "Contrats".
Le fichier importé doit être un "csv excel" (colonnes séparées par des ; notamment, avec le matricule dans la première colonne, et le temps de travail dans la 11ème colonne. Le temps de travail est un nombre décimal avec une virgule ou un point. Si c'est autre chose ("horasoc"...) on considère que ça signifie "temps plein".
