### ISSUE TITLE
demande de rencontre RH

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#87]
Juste pour vérifier, quand j'exporte les demandes de rencontre RH je n'ai que des entretiens de 2016.... je trouve ca étrange mais c'est peut-être effectivement le cas.
Juste vérifier si ca va bien chercher dans le dernier entretien de la personne... je crois que c'est ça qu'on avait défini

**Comment by Highbrainer** [comment]
Vérifié ensemble, si on ajoute une demande aujourd'hui, elle sort bien avec la bonne date dans l'export.
J'en ai profité pour t'afficher l'année de la date par défaut (avant c'était juste jour/mois).
