### ISSUE TITLE
export des formations

### ISSUE THREAD

**Issue by MagaliBorgoltz** [Highbrainer/jeevaneo#9]
il me faudrait un export des formations réalisées ou du moins enregistrées comme telle (si la formation n'est pas passée mais est enregistrée je la veux quand même)
il me semble qu'on avait fait un truc du genre l'année dernière au moment de l'audit qualité (une trame excel avec la liste des salariés, la liste des formations et une croix quand le salarié a fait une formation)
Mais là j'ai plus besoin d'une liste et après je ferai des tries.
Merci

**Comment by Highbrainer** [comment]
Magali veut un tableau "simple" avec les colonnes suivantes:
* etablissement
* nom
* prenom
* formation
* date de la session (début)
* durée de la session
* dpc?

**Comment by Highbrainer** [comment]
Inclus dans la 1.1!
